### PR TITLE
[Escrow Dashboard] fix: use env vars for RPC urls #1890

### LINKED ISSUE #1890: Dashboard - RPC urls as environment variables
**Description**
Set the RPC urls as environment variables

**Motivation**
Improve security of our RPCs

**Implementation details** 
If the RPC for a specific network is not passed, this network should be disabled.

### PR DESCRIPTION
**Pull request by leric7**
## Description

Use env vars for RPC urls in escrow dashboard project.

## Summary of changes

- Removed hard coded RPC urls and used env vars.
- Defined env vars on Vercel project.

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Closes #1890

### CODE REVIEW

**Review by flopez7 — APPROVED** [review]

File: packages/apps/dashboard/ui/src/constants/index.ts [hunk 1]
```diff
@@ -2,12 +2,10 @@ import { ChainId } from '@human-protocol/sdk';
 
 export const V2_SUPPORTED_CHAIN_IDS = [
   ChainId.MAINNET,
-  ChainId.GOERLI,
   ChainId.SEPOLIA,
   ChainId.BSC_MAINNET,
   ChainId.BSC_TESTNET,
   ChainId.POLYGON,
-  ChainId.POLYGON_MUMBAI,
```
Comment (Dzeranov) [inline packages/apps/dashboard/ui/src/constants/index.ts:10]: Adrian mentioned that on a dashboard we still have archive data about testnets. 
Will this change affect it?

Comment (leric7) [reply packages/apps/dashboard/ui/src/constants/index.ts:10]: I think this only removes the Mumbai option from the network selection from the UI. I guess the data itself is coming from the admin API, and if we still have archive data, we should fix backend API. BTW, I don't see those deprecated testnets inside supported chain list from admin API, though.
