### PR TITLE
fix: [SDK] KVStore keys

### LINKED ISSUE #1130: SDK - Fix KVStore keys
**Describe the bug**
KVStore keys from [this](https://github.com/humanprotocol/human-protocol/blob/main/packages/sdk/typescript/human-protocol-sdk/src/constants.ts) constants file on SDK should be like:
```
export const KVStoreKeys = {
  role: 'role',
  webhookUrl: 'webhookUrl',
  fee: 'fee',
  publicKey: 'publicKey',
};
```
Otherwise those keys will not be detected on subgraph.
Check if the same happen with Python and fix it also if so.

### PR DESCRIPTION
**Pull request by leric7**
## Summary of changes
- Changed KVStore keys of Webhook URL, and Public Key.
- Changed KVStore keys used from other places.

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Closes #1130

## Operational checklist

- [x] All new functionality is covered by tests
- [x] Any related documentation has been changed or added

### CODE REVIEW

File: packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts [hunk 1]
```diff
@@ -195,7 +195,7 @@ export class KVStoreClient {
    * const signer = new Wallet(privateKey, provider);
    * const kvstoreClient = await KVStoreClient.build(signer);
    *
-   * const keys = ['Role', 'Webhook_url'];
+   * const keys = ['Role', 'WebhookUrl'];
```
Comment (portuu3) [inline packages/sdk/typescript/human-protocol-sdk/src/kvstore.ts:198]: Use always same case to avoid case sensitive errors

```suggestion
   * const keys = ['role', 'webhookUrl'];
```

**Review by portuu3 — CHANGES_REQUESTED** [review]

**Review by portuu3 — APPROVED** [review]

**Review by portuu3 — CHANGES_REQUESTED** [review]
@leric7 you need to run `yarn build:doc` ts sdk so it updates docs/sdk/typescript/classes/kvstore.KVStoreClient.md

**Review by portuu3 — APPROVED** [review]
