### PR TITLE
fix: sdk staking client to add staker address when getting staker info

### LINKED ISSUE #648: Fix returned model when getting all stakers information
**Description**
Add staker address to the model returned by `getAllStakers` from typescript SDK and `get_all_stakers_info` from python SDK

**Motivation**
Without the address we don't know who is the data from

**Implementation details** 
Update returned model
Fix method
Fix tests

### PR DESCRIPTION
**Pull request by leric7**
## Description

Fix Node.js/Python SDK `StakingClient` module. It's missing address in the staker info, which is necessary.

## Summary of changes
- Updated return value schema of `getAllStakers`, and `getStaker` function of Node.js SDK, to include `address` of the staker.
- Updated `get_staker_info` function of Python SDK to include `address` of the staker.
- Renamed `staker` to `address` of the return value of `get_all_stakers_info` function, to unify the response schema with Node.js SDK.
- Updated relevant tests.

## Related issues
[Keywords for linking issues](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)

Closes #648 

## Operational checklist

- [x] All new functionality is covered by tests
- [x] Any related documentation has been changed or added

### CODE REVIEW

File: packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts [hunk 1]
```diff
@@ -22,6 +22,10 @@ export interface IStaker {
   tokensAvailable: BigNumber;
 }
 
+export interface IStakerWithAddress extends IStaker {
```
Comment (portuu3) [inline packages/sdk/typescript/human-protocol-sdk/src/interfaces.ts:25]: Why this extension instead of just adding address?

**Review by portuu3 — CHANGES_REQUESTED** [review]
lets keep it as staker or stakerAddress instead of address
